# hydra config
hydra:
  run:
    dir: /workspace/code/logs/${train.experiment}/${model.model}/${now:%Y-%m-%d}/${model.model_class_num}/${now:%H-%M-%S}

optimizer:
  lr: 0.0001
  beta1: 0.5
  beta2: 0.999

data:
  background: black # ['white', 'black', 'non']
  data_path: /workspace/data/pendulum_${data.background}/raw/data/
  index_path: /workspace/data/pendulum_${data.background}/raw/index_mapping/
  config_path: /workspace/data/pendulum_${data.background}/config/
  # temp_save_fig_path: /workspace/data/pendulum/temp_fig/
  class_to_num: /workspace/data/pendulum_${data.background}/class_to_num.json  # the class to num mapping

  num_workers: 4
  img_size: 224
  # sampling: "over" # over, under, none

  batch_size: 16  # this used for default method, without gait cycle defined method.
  val_ratio: 0.2

model:
  model: "resnet"   
  model_class_num: 9
  model_depth: 50 # choices=[50, 101, 152], help='the depth of used model'

train:
  # Training config
  max_epochs: 50 # numer of epochs of training

  # used for val 
  clip_duration: 1 # clip duration for the video
  uniform_temporal_subsample_num: 16 # num frame from the clip duration, f or define one gait cycle, we need use whole frames.

  experiment: temporal_mix # temporal_mix, single_stance, single_swing, single_random, late_fusion

  gpu_num: 0 # choices=[0, 1], help='the gpu number whicht to train'

  # Transfor_learning
  transfor_learning: True # if use the transformer learning

  log_path: /workspace/code/logs/${train.experiment}/${model.model}/${now:%Y-%m-%d}/${model.model_class_num}/${now:%H-%M-%S}

  fast_dev_run: False # if use the fast_dev_run
  fold: 3 # the fold number of the cross validation