# hydra config
hydra:
  run:
    dir: /workspace/code/logs/${train.experiment}/${model.model}/${now:%Y-%m-%d}/${model.model_class_num}/${now:%H-%M-%S}

optimizer:
  lr: 0.0001
  beta1: 0.5
  beta2: 0.999

data:
  data_path: /workspace/data/pendulum/data/
  index_path: /workspace/data/pendulum/index_mapping/
  config_path: /workspace/data/pendulum/config/
  # temp_save_fig_path: /workspace/data/pendulum/temp_fig/

  num_workers: 4
  img_size: 224
  # sampling: "over" # over, under, none

  gait_cycle_batch_size: 1 # this used for gait cycle defined method. 
  default_batch_size: 32  # this used for default method, without gait cycle defined method.

model:
  model: "resnet"   
  model_class_num: 4 
  model_depth: 50 # choices=[50, 101, 152], help='the depth of used model'

train:
  # Training config
  max_epochs: 50 # numer of epochs of training

  # used for val 
  clip_duration: 0.5 # clip duration for the video
  uniform_temporal_subsample_num: 8 # num frame from the clip duration, f or define one gait cycle, we need use whole frames.

  experiment: temporal_mix # temporal_mix, single_stance, single_swing, single_random

  gpu_num: 0 # choices=[0, 1], help='the gpu number whicht to train'

  # Transfor_learning
  transfor_learning: True # if use the transformer learning

  log_path: /workspace/code/logs/${train.experiment}/${model.model}/${now:%Y-%m-%d}/${model.model_class_num}/${now:%H-%M-%S}

  fast_dev_run: False # if use the fast_dev_run
  fold: 3 # the fold number of the cross validation

  gait_cycle: 0 # [0, 1, -1] swing phase, stance phase, random phase. when temporal_mix=true, it does not work.